import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mainContainer}>
        <div className={styles.todoListBox}>
          <div className={styles.todoListInputContainer}>
            <a>Todo List</a>
            <div>
              <input placeholder='Digite uma pendência'/>
              <button>Adicionar</button>
            </div>
          </div>
          <div className={styles.todoListFunctionsButtons}>
            <button>Todos</button>
            <button>Completas</button>
            <button>Para fazer</button>
          </div>
          <div className={styles.todoListTotalContainer}>
            <div className={styles.todoListContainer}>
              <input type="checkbox" />
              <a>examplename</a>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
